[build]
  command = "npm install --force --legacy-peer-deps && npm run build:ssr"
  publish = "dist/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"
