[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build:ssr"
  publish = "dist/stroyka/browser"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[functions]]
  directory = "functions"
  external_node_modules = ["express"]
