[build]
  command = "npm i --legacy-peer-deps && npm run build:ssr"
  publish = "dist/browser"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  PORT = "4000"
