[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build:ssr"
  publish = "dist/stroyka/browser"

[functions]
  directory = "functions"
  external_node_modules = ["express"]
