[build]
  command = "npm run build:ssr"
  publish = "dist/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[npm]
install-args = "--force"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
