[build]
  command = "npm install --force --legacy-peer-deps && npm run build:ssr && cp -r dist/server/* dist/browser/"
  publish = "dist/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[dev]
  command = "npm run serve:ssr"
  targetPort = 4000
