[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build:ssr"
  publish = "dist/browser"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
